# Generated by Django 4.1.13 on 2025-09-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('agronomist', 'Agronomist')], default='farmer', max_length=20),
        ),
    ]
