# Generated by Django 4.1.13 on 2025-08-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_farmer_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='farmer',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pics/default_profile.png', null=True, upload_to='profile_image/'),
        ),
    ]
