# Generated by Django 4.1.13 on 2025-09-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropdisease',
            name='area_affected',
            field=models.CharField(choices=[('leaves', 'Leaves'), ('stems', 'Stems'), ('fruits', 'Fruits')], default='leaves', max_length=10),
        ),
        migrations.AddField(
            model_name='cropdisease',
            name='solution_type',
            field=models.CharField(choices=[('cultural_control', 'Cultural and Preventive Practices'), ('chemical_control', 'Chemical Control')], default='cultural_control', max_length=20),
        ),
    ]
