# Generated by Django 4.1.13 on 2025-09-08 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agronomist_app', '0002_cropdisease_area_affected_cropdisease_solution_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthyCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=200)),
                ('characteristics', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agronomist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthyCropImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='healthy_crop_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agronomist_app.healthycrop')),
            ],
        ),
    ]
